### ISSUE TITLE
How we can create datasets from S3 bucket using cli.

### ISSUE THREAD

**Issue by hk1313** [awsdocs/amazon-rekognition-custom-labels-developer-guide#1]
Here is ref for creating dataset, images from device as well as from S3 bucket.   https://docs.aws.amazon.com/rekognition/latest/customlabels-dg/gs-step-create-dataset.html.  How we can do that same thing using cli. Let's assume I already uploaded my images in one S3 bucket.

**Comment by AWSChris** [comment]
Hi,  You can't create a Custom Labels dataset using the CLI/SDK. If you're image are already in S3 you can use the console to create the dataset. If you don't want to use the console, you could train the model using a manifest file that you create, however the dataset won't be available in the console. Info on create a manifest file - https://docs.aws.amazon.com/rekognition/latest/customlabels-dg/cd-manifest-files.html. Training a model with the SDK - https://docs.aws.amazon.com/rekognition/latest/customlabels-dg/tm-sdk.html.
