### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by JanTrichter** [awsdocs/amazon-rekognition-custom-labels-developer-guide#3]
The link to the AWS CLI tutorial on [this page](https://docs.aws.amazon.com/rekognition/latest/customlabels-dg/su-awscli-sdk.html) is not working as it is supposed to be.

The link points to `https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install` => broken
although it should actually point to `https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html`

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
